# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/FOTH0626"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/351177307"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "mail"
name = "Gmail"
url = "mailto:fothli0626@gmail.com"

[social.params]
icon = "mail"
